name: Update Gist

on:
  push:
    branches:
      - main  # Workflow запускается при пуше в ветку main
    paths:
      - 987503925/main.css  # Путь к файлу в репозитории, который отслеживаем

jobs:
  update-gist:
    runs-on: ubuntu-latest
    env:
      FILE_NAME: "987503925/main.css"  # Полный путь к файлу в репозитории

    steps:
      - uses: actions/checkout@v3  # Шаг для клонирования репозитория

      - name: Use variable in step
        run: |
          echo "We are using file: $FILE_NAME"  # Лог для проверки имени файла

      - name: Update Gist
        run: |
          GIST_ID="acc3625e6b059b7fd3f898949456d4bf"  # Укажи ID своего Gist
          echo "Updating Gist with file: $FILE_NAME"
          curl \
            -X PATCH \
            -H "Authorization: token ${{ secrets.GIST_SECRET_TOKEN }}" \  # Используем токен из секретов
            -d "$(jq -n --arg content "$(cat $FILE_NAME)" '{"files": {"987503925.css": {"content": $content}}}')" \  # Важное изменение: имя файла в Gist — "987503925.css"
            https://api.github.com/gists/$GIST_ID
