name: Update Gist 987503925

on:
  push:
    branches:
      - main  # Срабатывает при изменениях в ветке main
    paths:
      - posts/987503925.css  # Отслеживаем изменения в конкретной папке

jobs:
  update-gist:
    runs-on: ubuntu-latest
    env:
      FILE_NAME: "posts/987503925.css"  # Путь к файлу в репозитории

    steps:
      - uses: actions/checkout@v3
      - name: Update Gist
        run: |
          GIST_ID="7466013e1a8588e8a8e223ee2644d69f"
          curl \
            -X PATCH \
            -H "Authorization: token ${{ secrets.GIST_SECRET_TOKEN }}" \
            -d "$(jq -n --arg content "$(cat $FILE_NAME)" '{"files": {"main.css": {"content": $content}}}')" \
            https://api.github.com/gists/$GIST_ID
